### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by leissler** [jlreymendez/planilo#9]
The last commit to even the development branch seems something like 11 months old. 
Could you elaborate on the state of this very interesting project?

**Comment by jlreymendez** [comment]
Hi, I am not actively working on it as you can tell from the time since the latest commits. Main reason for this is because I have no project that requires it for now. As I was developing 0.2 I realized that this project works more like as an example or prototype of how to use xNode for such a goal, since the tool's responsibilities have been simplified to the point where it is just about serializing the behavior tree. Scheduling of behaviors and the logic of the nodes is all under the users purview.

I believe I should close version 0.2 with the current development branch as it is stable. Although the samples were having some assets issues in Unity 2019, I believe these issues don't apply to user assets, but I can't be sure again since I haven't used it in one of my projects yet. 

If I ever continue working on this, I would probably focus mainly on making it compatible with Unity jobs which I already know requires a rethinking of the state data of nodes.
